handler: infra/serverless/resources/lambda/handlers/listEntries/handler.main
events:
  - http:
      path: ecg
      method: get
      cors: true
iamRoleStatementsName: listEntries-lambda-role
iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
    Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/ECGTable"