Resources:
  EcgTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'ECGTable'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
        - AttributeName: 'milivolts'
          AttributeType: 'N'
        - AttributeName: 'deviceId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
        - AttributeName: 'milivolts'
          KeyType: 'RANGE'
      GlobalSecondaryIndexes:
        - IndexName: 'DeviceIdIndex'
          KeySchema: 
            - AttributeName: 'devideId'
              AttributeType: 'S'
      #StreamSpecification:
      #  StreamViewType: 'NEW_IMAGE'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5