handler: infra/serverless/resources/lambda/handlers/createEntries/handler.main
events:
  - http:
      path: ecg
      method: post
      cors: true
iamRoleStatementsName: createEntries-lambda-role
iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:CreateTable
    Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/ECGTable*"