handler: infra/serverless/resources/lambda/handlers/createEntries/handler.main
events:
  - http:
      path: ecg
      method: post
      cors: true
iamRoleStatementsName: createEntries-lambda-role
iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:PutItem
    Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/ECGTable"