app: ecg-api
service: ecg-api

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: 'node20'
    platform: 'node'
    concurrency: 10

functions:
  - ${file(./lambda/handlers/createEntries/createEntries.yml)}