handler: infra/serverless/resources/lambda/handlers/listIrregularities/handler.main
events:
  - http:
      path: ecg/irregularities
      method: get
      cors: true
iamRoleStatementsName: listIrregularities-lambda-role
iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:CreateTable
    Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/ECGTable*"