app: ecg-api
service: ecg-api

plugins:
  - serverless-iam-roles-per-function


provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: production
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: 'node20'
    platform: 'node'
    concurrency: 10

functions:
  createECGEntries: ${file(./infra/serverless/resources/lambda/handlers/createEntries/createEntries.yml)}

resources:
  Resources:
    ECGTable: ${file(./infra/serverless/resources/dynamodb/ecgTable.yml)}