name: Build, Test, Release and Deploy

on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - master

jobs:
  filter-changes:
    runs-on: ubuntu-latest
    outputs:
      ecg-api: ${{ steps.filter.outputs.ecg-api }}
      hbm-plus: ${{ steps.filter.outputs.hbm-plus }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            ecg-api:
              - 'packages/ecg-api/**'
            hbm-plus:
              - 'packages/hbm-plus/**'

  build-ecg-api:
    needs: filter-changes
    if: needs.filter-changes.outputs.ecg-api == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          cd packages/ecg-api
          npm test

  release-ecg-api:
    runs-on: ubuntu-latest
    needs: build-ecg-api

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Use the version of Node.js you need

      - name: Install dependencies
        run: |
          npm install

      - name: Run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd packages/ecg-api 
          npx semantic-release

  deploy-ecg-api:
    runs-on: ubuntu-latest
    needs: release-ecg-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Serverless Framework
        run: |
          cd packages/ecg-api  
          npm install -g serverless

      - name: Deploy with Serverless
        run: |
          cd packages/ecg-api 
          serverless deploy --stage production --verbose
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-hbm-plus:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  release-hbm-plus:
    runs-on: ubuntu-latest
    needs: build-hbm-plus

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release

  deploy-hbm-plus:
    runs-on: ubuntu-latest
    needs: release-hbm-plus

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/hbm-plus .
        docker push ${{ secrets.DOCKER_USERNAME }}/hbm-plus

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/hbm-plus registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
        docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
        heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}